### ISSUE TITLE
TypeError: Couldn't build proto file into descriptor pool

### ISSUE THREAD

**Issue by zhonhel** [facebookresearch/vilbert-multi-task#102]
I fixed numpy version error in requirements.txt.

Now I want to execute this command:
```
python train_tasks.py --bert_model bert-base-uncased --from_pretrained {path to}/multi_task_model.bin --config_file config/bert_base_6layer_6conect.json --tasks 1-2-4-7-8-9-10-11-12-13-15-17 --lr_scheduler 'warmup_linear' --train_iter_gap 4 --task_specific_tokens --save_name multi_task_model
```
I encountered the error:
```
2021-06-25 11:22:37.444926: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "train_tasks.py", line 33, in <module>
    from vilbert.task_utils import (
  File "/LocalRun/home/shihao.wang/vilbert-multi-task/vilbert/task_utils.py", line 19, in <module>
    from vilbert.datasets import DatasetMapTrain, DatasetMapEval
  File "/LocalRun/home/shihao.wang/vilbert-multi-task/vilbert/datasets/__init__.py", line 6, in <module>
    from .concept_cap_dataset import (
  File "/LocalRun/home/shihao.wang/vilbert-multi-task/vilbert/datasets/concept_cap_dataset.py", line 15, in <module>
    import tensorpack.dataflow as td
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorpack/__init__.py", line 5, in <module>
    from tensorpack.libinfo import __version__, __git_version__, _HAS_TF
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorpack/libinfo.py", line 53, in <module>
    import tensorflow as tf  # noqa
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/__init__.py", line 55, in <module>
    from ._api.v2 import compat
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/_api/v2/compat/__init__.py", line 39, in <module>
    from . import v1
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 34, in <module>
    from . import compat
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 40, in <module>
    from . import v2
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 32, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 37, in <module>
    from . import compat
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 40, in <module>
    from . import v2
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 331, in <module>
    from tensorboard.summary._tf import summary
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 21, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/plugins/audio/summary.py", line 34, in <module>
    from tensorboard.plugins.audio import metadata
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/plugins/audio/metadata.py", line 18, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 23, in <module>
    serialized_pb=_b('\n+tensorboard/compat/proto/tensor_shape.proto\x12\x0btensorboard\"{\n\x10TensorShapeProto\x12.\n\x03\x64im\x18\x02 \x03(\x0b\x32!.tensorboard.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
  File "/LocalRun/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 983, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/compat/proto/tensor_shape.proto":
  tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.unknown_rank: "tensorboard.TensorShapeProto.unknown_rank" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim.size: "tensorboard.TensorShapeProto.Dim.size" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim.name: "tensorboard.TensorShapeProto.Dim.name" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim: "tensorboard.TensorShapeProto.Dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto: "tensorboard.TensorShapeProto" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.Dim" seems to be defined in "tensorboardX/src/tensor_shape.proto", which is not imported by "tensorboard/compat/proto/tensor_shape.proto".  To use it here, please add the necessary import.

```

**Comment by snowyrain** [comment]
I have the same problem

**Comment by charliecaffe** [comment]
solved by this [https://github.com/facebookresearch/vilbert-multi-task/issues/14#issuecomment-613439189]
