### ISSUE TITLE
requirements.txt   update

### ISSUE THREAD

**Issue by moutaigua8183** [facebookresearch/vilbert-multi-task#14]
1.  
pytorch-transformers==1.0.0  does not provide implementation for RoBERTa model.  The support starts from 1.1.0.   With pytorch-transformers==1.0.0,   it gives me errors when running the training script.
2. 
tensorboardX==1.2
tensorflow==1.15.2
tensorpack==0.9.4
For some reasons,  I have the following errors when running the scripts. I am wondering if there are any conflicts
`
Traceback (most recent call last):
  File "/home/mou/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/mou/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/mou/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mou/Desktop/evqa/vilbert-multi-task/train_evqa.py", line 33, in <module>
    from vilbert.task_utils import (
  File "/home/mou/Desktop/evqa/vilbert-multi-task/vilbert/task_utils.py", line 20, in <module>
    from vilbert.datasets import DatasetMapTrain, DatasetMapEval
  File "/home/mou/Desktop/evqa/vilbert-multi-task/vilbert/datasets/__init__.py", line 6, in <module>
    from .concept_cap_dataset import (
  File "/home/mou/Desktop/evqa/vilbert-multi-task/vilbert/datasets/concept_cap_dataset.py", line 15, in <module>
    import tensorpack.dataflow as td
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorpack/__init__.py", line 5, in <module>
    from tensorpack.libinfo import __version__, __git_version__, _HAS_TF
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorpack/libinfo.py", line 53, in <module>
    import tensorflow as tf  # noqa
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorflow_core/_api/v1/compat/__init__.py", line 24, in <module>
    from tensorflow._api.v1.compat import v2
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorflow_core/_api/v1/compat/v2/__init__.py", line 322, in <module>
    from tensorboard.summary._tf import summary
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 24, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/plugins/audio/summary.py", line 36, in <module>
    from tensorboard.plugins.audio import metadata
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/plugins/audio/metadata.py", line 21, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 23, in <module>
    serialized_pb=_b('\n+tensorboard/compat/proto/tensor_shape.proto\x12\x0btensorboard\"{\n\x10TensorShapeProto\x12.\n\x03\x64im\x18\x02 \x03(\x0b\x32!.tensorboard.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tBq\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
  File "/home/mou/miniconda3/envs/evqa/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/compat/proto/tensor_shape.proto":
  tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.unknown_rank: "tensorboard.TensorShapeProto.unknown_rank" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim.size: "tensorboard.TensorShapeProto.Dim.size" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim.name: "tensorboard.TensorShapeProto.Dim.name" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim: "tensorboard.TensorShapeProto.Dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto: "tensorboard.TensorShapeProto" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.Dim" seems to be defined in "tensorboardX/src/tensor_shape.proto", which is not imported by "tensorboard/compat/proto/tensor_shape.proto".  To use it here, please add the necessary import.
`

**Comment by bhoomit** [comment]
@moutaigua8183 Were you able to solve the problem?

**Comment by moutaigua8183** [comment]
> @moutaigua8183 Were you able to solve the problem?

I had it fixed by trying different combination of packages of different version, and end up withing the following one:

**Comment by bhoomit** [comment]
@moutaigua8183 let me give it a try

**Comment by bhoomit** [comment]
> > @moutaigua8183 Were you able to solve the problem?
> 
> I had it fixed by trying different combination of packages of different version, and ended up with the following setting:
> tensorboardX==1.8
> pytorch-transformers==1.1.0
> tensorpack==0.9.4

Awesome. This works :)

**Comment by e-commerce-search** [comment]
I get this error after swapping those modules above: 

Traceback (most recent call last):
  File "train_concap.py", line 30, in <module>
    from vilbert.datasets import ConceptCapLoaderTrain, ConceptCapLoaderVal
  File "t/vilbert-multi-task-master/vilbert/datasets/__init__.py", line 15, in <module>
    from .refer_expression_dataset import ReferExpressionDataset
  File "/vilbert-multi-task-master/vilbert/datasets/refer_expression_dataset.py", line 16, in <module>
    from tools.refer.refer import REFER
ModuleNotFoundError: No module named 'tools.refer.refer'

**Comment by Tahlor** [comment]
> I get this error after swapping those modules above:
> 
> Traceback (most recent call last):
> File "train_concap.py", line 30, in
> from vilbert.datasets import ConceptCapLoaderTrain, ConceptCapLoaderVal
> File "t/vilbert-multi-task-master/vilbert/datasets/**init**.py", line 15, in
> from .refer_expression_dataset import ReferExpressionDataset
> File "/vilbert-multi-task-master/vilbert/datasets/refer_expression_dataset.py", line 16, in
> from tools.refer.refer import REFER
> ModuleNotFoundError: No module named 'tools.refer.refer'

You'll need to:

- clone https://github.com/lichengunc/refer/tree/d23ec5d8e84baf858c58af119799e26846aa5261 to the `./tools/refer` folder
- Run `make` inside that folder

**Comment by KAndHisC** [comment]
> I get this error after swapping those modules above:
> 
> Traceback (most recent call last):
> File "train_concap.py", line 30, in
> from vilbert.datasets import ConceptCapLoaderTrain, ConceptCapLoaderVal
> File "t/vilbert-multi-task-master/vilbert/datasets/**init**.py", line 15, in
> from .refer_expression_dataset import ReferExpressionDataset
> File "/vilbert-multi-task-master/vilbert/datasets/refer_expression_dataset.py", line 16, in
> from tools.refer.refer import REFER
> ModuleNotFoundError: No module named 'tools.refer.refer'

hey guy, I found nobody mentioned that should switch to the 'python3' branch.
that one -> https://github.com/lichengunc/refer/tree/python3
