### ISSUE TITLE
Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS

### ISSUE THREAD

**Issue by gabrielilharco** [facebookresearch/vilbert-multi-task#25]
Hi,

Following the visual feature extraction instructions, I'm running into the following issue:

>Traceback (most recent call last):
  File "../vilbert-multi-task/script/extract_features.py", line 233, in <module>
    feature_extractor = FeatureExtractor()
  File "../vilbert-multi-task/script/extract_features.py", line 30, in __init__
    self.detection_model = self._build_detection_model()
  File "../vilbert-multi-task/script/extract_features.py", line 76, in _build_detection_model
    cfg.merge_from_file(self.args.config_file)
  File "/home/gamaga/anaconda3/envs/multimodalqa/lib/python3.8/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/gamaga/anaconda3/envs/multimodalqa/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/gamaga/anaconda3/envs/multimodalqa/lib/python3.8/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/gamaga/anaconda3/envs/multimodalqa/lib/python3.8/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/gamaga/anaconda3/envs/multimodalqa/lib/python3.8/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'

From [this issue](https://github.com/chengyangfu/retinamask/issues/7) it seems like that the config provided here might not be consistent with maskrcnn current code. Is there any particular version I should install?

**Comment by gabrielilharco** [comment]
See also [here](https://github.com/facebookresearch/maskrcnn-benchmark/issues/563)

**Comment by vedanuj** [comment]
Please follow the steps in readme here : https://github.com/facebookresearch/vilbert-multi-task/tree/master/data

The maskrcnn benchmark repo should be exatcly the same as provided in the readme.

**Comment by doppelbeaver** [comment]
Looking forward to this. I have the same problem

**Comment by sufferjoy** [comment]
I have the same problem, and seems that MODEL.BACKBONE.OUT_CHANNELS is not defined in the config of maskrcnn. Have you worked this out?

**Comment by leyuan** [comment]
The problem is due to the recent version of mask-rcnn repo, I used the version here:
https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark/-/tree/master

**Comment by gabrielilharco** [comment]
@leyuan, did you follow the instructions there on INSTALL.md? It seems it is just cloning the most recent maskrcnn-benchmark git repo. I noticed there is a maskrcnn-benchmark on the vqa-maskrcnn-benchmark repo, but setup.py

**Comment by leyuan** [comment]
Hi @gabrielilharco, I think I saw that instruction somewhere when I first tried it and worked. I realize now it is not the same, I also went down the path of using the github repo but didn't work, so I just stick with that gitlb repo.

**Comment by dixonhsiao** [comment]
Hi @leyuan , so which maskrcnn checkout did you use exactly ? I have exactly the same problem...

**Comment by seo-95** [comment]
> Hi @leyuan , so which maskrcnn checkout did you use exactly ? I have exactly the same problem...

Hi solved by installing the other repo:

```
$ git clone https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark.git
$  cd vqa-maskrcnn-benchmark/
$ python setup.py build develop
```

**Comment by Jack-lx-jiang** [comment]
```
$ git clone https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark.git
$ cd vqa-maskrcnn-benchmark/
$ python setup.py build develop
```
I used these commands to install, but unfortunately still got the same error.
Any ideas what happened?

**Comment by seo-95** [comment]
> ```
> $ git clone https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark.git
> $ cd vqa-maskrcnn-benchmark/
> $ python setup.py build develop
> ```
> 
> I used these commands to install, but unfortunately still got the same error.
> Any ideas what happened?

You can try to follow this [](https://github.com/seo-95/vilbert-multi-task#repository-setup-with-python-virtualenv), I was trying to make an updated vilbert installation

**Comment by Jack-lx-jiang** [comment]
sorry, I made a stupid mistake..... uploaded a wrong project to the server....   so, just ignore my last comment.

**Comment by snowyrain** [comment]
> > Hi @leyuan , so which maskrcnn checkout did you use exactly ? I have exactly the same problem...
> 
> I solved by installing the other repo:
> 
> ```
> $ git clone https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark.git
> $ cd vqa-maskrcnn-benchmark/
> $ python setup.py build develop
> ```



> > Hi @leyuan , so which maskrcnn checkout did you use exactly ? I have exactly the same problem...
> 
> I solved by installing the other repo:
> 
> ```
> $ git clone https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark.git
> $ cd vqa-maskrcnn-benchmark/
> $ python setup.py build develop
> ```

it cant work to me
