### ISSUE TITLE
msgpack.exceptions.ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by convnets** [facebookresearch/vilbert-multi-task#31]
When running preprocess_sequential_train_segment.py, I got this error. Any ideas?

```
Process _Worker-1:
Traceback (most recent call last):
  File "/home/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/tensorpack/dataflow/parallel.py", line 285, in run
    for dp in self.ds:
  File "/home/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/tensorpack/dataflow/common.py", line 297, in __iter__
    ret = self.func(copy(dp))  # shallow copy the list
  File "/home/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/tensorpack/dataflow/serialize.py", line 84, in <lambda>
    return MapData(df, lambda dp: loads(dp[1]))
  File "/home/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/tensorpack/utils/serialize.py", line 43, in loads_msgpack
    max_str_len=MAX_MSGPACK_LEN)
  File "/home/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/msgpack_numpy.py", line 255, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

**Comment by vedanuj** [comment]
Please use train_concap.py or train_tasks.py
