### ISSUE TITLE
Referred Object Comprehension code is in python 2

### ISSUE THREAD

**Issue by bhargavaurala** [facebookresearch/vilbert-multi-task#33]
Hello,

I am trying to use reproduce train and test performance using this repository however one of the external packages in tools/refer seems to be written in python2.

Am I looking at the wrong version or is there any workaround apart from converting the print statements (which seem to be the culprit for now?)

Please let me know.

**Comment by AIstudentSH** [comment]
May I ask how to modify the compatibility in py3? I can't find a suitable cPickle package.

**Comment by vedanuj** [comment]
After you update the submodule you can replace the refer.py with this https://gist.github.com/vedanuj/9d3497d107cfca0b6f3dfdc28d5cb226

That should work.

**Comment by galsk87** [comment]
Have the same issue.
I did what you said and I still get the error:

Traceback (most recent call last):
  File "eval_tasks.py", line 26, in <module>
    from vilbert.task_utils import (
  File "/home/gal/vilbert-multi-task/vilbert/task_utils.py", line 19, in <module>
    from vilbert.datasets import DatasetMapTrain, DatasetMapEval
  File "/home/gal/vilbert-multi-task/vilbert/datasets/__init__.py", line 15, in <module>
    from .refer_expression_dataset import ReferExpressionDataset
  File "/home/gal/vilbert-multi-task/vilbert/datasets/refer_expression_dataset.py", line 16, in <module>
    from tools.refer.refer import REFER
  File "/home/gal/vilbert-multi-task/tools/refer/refer.py", line 39, in <module>
    from external import mask
ImportError: cannot import name 'mask'

**Comment by RenShuhuai-Andy** [comment]
I have the same issue @galsk87 
How did you solve it?

**Comment by galsk87** [comment]
I didn't

בתאריך יום ד׳, 16 בספט׳ 2020, 12:21, מאת Shuhuai Ren ‏<
notifications@github.com>:

**Comment by RenShuhuai-Andy** [comment]
```
cd vilbert-multi-task/tools/refer
python setup.py install
make
```
It works for me.
reference: [https://github.com/cocodataset/cocoapi/issues/272](https://github.com/cocodataset/cocoapi/issues/272)
