### ISSUE TITLE
msgpack.exceptions.ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by Jack-lx-jiang** [facebookresearch/vilbert-multi-task#46]
Hi,

When I tried to run
```
python train_concap.py --bert_model bert-base-uncased \
                       --config_file config/bert_base_6layer_6conect.json \
                       --train_batch_size 512 --objective 1 \
                       --file_path ../cc_dataset/dataset \
                       --output_dir ../vilbert_files/models
```

I got the error message below:

```
Process _Worker-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 169, in run
    for dp in self.ds:
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 641, in __iter__
    for dp in self._inf_iter:
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 370, in __iter__
    for dp in self.ds:
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 297, in __iter__
    ret = self.func(copy(dp))  # shallow copy the list
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/dataflow/serialize.py", line 84, in <lambda>
    return MapData(df, lambda dp: loads(dp[1]))
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/utils/serialize.py", line 43, in loads_msgpack
    max_str_len=MAX_MSGPACK_LEN)
  File "/usr/local/python3/lib/python3.6/site-packages/msgpack_numpy.py", line 255, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 208, in msgpack._unpacker.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

Do you have any ideas what happens?
Thanks!

**Comment by theDragonSlayer97** [comment]
Same error... would highly appreciate any ideas.

**Comment by trungtv** [comment]
You may try the following package versions. It works for my side. 
pytorch-transformers==1.0.0
numpy==1.16.4
lmdb==0.94
**tensorboardX==2.0**
tensorflow==1.15.2
**tensorpack==0.10.1**
tqdm==4.31.1
easydict==1.9
PyYAML==5.1.2
jsonlines==1.2.0
json-lines==0.5.0
matplotlib
Cython
python-prctl
msgpack
msgpack-numpy
opencv-python==4.2.0.34
