### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.refer.refer'

### ISSUE THREAD

**Issue by lzh66** [facebookresearch/vilbert-multi-task#52]
!python train_tasks.py --bert_model bert-base-uncased --from_pretrained data/pretrained_model.bin --config_file config/bert_base_6layer_6conect.json --tasks 1-2-4-7-8-9-10-11-12-13-15-17 --lr_scheduler 'warmup_linear' --train_iter_gap 4 --task_specific_tokens --save_name multi_task_model

output:
2020-07-21 14:05:52.998850: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "train_tasks.py", line 33, in <module>
    from vilbert.task_utils import (
  File "/content/drive/My Drive/vilbert-multi-task-master/vilbert/task_utils.py", line 19, in <module>
    from vilbert.datasets import DatasetMapTrain, DatasetMapEval
  File "/content/drive/My Drive/vilbert-multi-task-master/vilbert/datasets/__init__.py", line 15, in <module>
    from .refer_expression_dataset import ReferExpressionDataset
  File "/content/drive/My Drive/vilbert-multi-task-master/vilbert/datasets/refer_expression_dataset.py", line 16, in <module>
    from tools.refer.refer import REFER
ModuleNotFoundError: No module named 'tools.refer.refer'

**Comment by tranvansanghust** [comment]
You should clone this repository: https://github.com/lichengunc/refer/tree/d23ec5d8e84baf858c58af119799e26846aa5261
After that, you have to make file to use it.

**Comment by enaserianhanzaei** [comment]
@lzh66 @tranvansanghust 

I wrote a step-by-step tutorial on how to set up the environment, train and test this model. I also added a section on extracting the visiolinguistic embeddings from the image-text data.
https://naserian-elahe.medium.com/vilbert-a-model-for-learning-joint-representations-of-image-content-and-natural-language-47f56a313a79
I very much appreciate any comments or suggestions

**Comment by wangying1586** [comment]
> !python train_tasks.py --bert_model bert-base-uncased --from_pretrained data/pretrained_model.bin --config_file config/bert_base_6layer_6conect.json --tasks 1-2-4-7-8-9-10-11-12-13-15-17 --lr_scheduler 'warmup_linear' --train_iter_gap 4 --task_specific_tokens --save_name multi_task_model
> 
> output:
> 2020-07-21 14:05:52.998850: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
> File "train_tasks.py", line 33, in
> from vilbert.task_utils import (
> File "/content/drive/My Drive/vilbert-multi-task-master/vilbert/task_utils.py", line 19, in
> from vilbert.datasets import DatasetMapTrain, DatasetMapEval
> File "/content/drive/My Drive/vilbert-multi-task-master/vilbert/datasets/**init**.py", line 15, in
> from .refer_expression_dataset import ReferExpressionDataset
> File "/content/drive/My Drive/vilbert-multi-task-master/vilbert/datasets/refer_expression_dataset.py", line 16, in
> from tools.refer.refer import REFER
> ModuleNotFoundError: No module named 'tools.refer.refer'

Could u tell me about this problem ? What should i do to solve it?
