### ISSUE TITLE
ModuleNotFoundError: No module named 'multimodal_bert'

### ISSUE THREAD

**Issue by goonmeet** [facebookresearch/vilbert-multi-task#74]
HI!

I am trying to use the eval_coco_retrieval script. However, I am running into the following error:

  File "evaluation/eval_coco_retrieval.py", line 33, in <module>
    from multimodal_bert.datasets import COCORetreivalDatasetTrain, COCORetreivalDatasetVal
ModuleNotFoundError: No module named 'multimodal_bert'

I am not sure what package I am missing.

Thanks in advance!

**Comment by prashan** [comment]
I am running into the same error....is there a package i need to install?
```
python $xxxx/evaluation/eval_refer_expression.py -h
Traceback (most recent call last):
  File "/xxxx/eval_refer_expression.py", line 30, in <module>
    from multimodal_bert.datasets import ReferExpressionDataset
ModuleNotFoundError: No module named 'multimodal_bert'
```

**Comment by lizizhong** [comment]
I think this module is here:  https://github.com/facebookresearch/vilbert-multi-task/tree/b1397820e8326fc0691594dea9daaeac908952fc
